cat <<EOF | kubectl apply -f -
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: notify-slack
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-secret
  namespace: notify-slack
stringData:
  apiKey: <api-token>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-cluster-secret
  namespace: "kargo-cluster-secrets"
stringData:
  apiKey: <api-token>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: notify-slack
  namespace: notify-slack
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.26.0
      discoveryLimit: 5
---
apiVersion: ee.kargo.akuity.io/v1alpha1
kind: NotificationChannel
metadata:
  name: slack
  namespace: notify-slack
spec:
  slack:
    channelID: C08CWPFBWLA
    secretRef:
      name: slack-secret
---
apiVersion: ee.kargo.akuity.io/v1alpha1
kind: ClusterNotificationChannel
metadata:
  name: slack-cluster
spec:
  slack:
    channelID: C08CWPFBWLA
    secretRef:
      name: slack-cluster-secret
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: notify-slack
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: notify-slack
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: notify
        config:
          message: "Hello, world"
          channel:
            kind: NotificationChannel
            name: slack
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: notify-slack
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: notify-slack
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - uses: notify
        config:
          message: "Promotion triggered for project Project on stage Stage for promotion Promotion"
          channel:
            kind: ClusterNotificationChannel
            name: slack-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-controller-secret-reader
  namespace: notify-slack
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-controller-secret-reader
  namespace: notify-slack
subjects:
- kind: ServiceAccount
  name: kargo-controller
  namespace: kargo
roleRef:
  kind: Role
  name: kargo-controller-secret-reader
  apiGroup: rbac.authorization.k8s.io
EOF
